schema_version = 2
name = "ducklake"
extension_config = "extension_config_vane.cmake"
build_extensions = ["httpfs", "parquet", "sqlite_scanner"]
native_test_selection = "test/sql/vane/*"

[vane]
repository = "AstroVela/vane"
revision = "4a85ae05d89b0194ac57f18bbfe22593cdec00c8"

[vcpkg]
repository = "microsoft/vcpkg"
revision = "84bab45d415d22042bd0b9081aea57f362da3f35"
