schema_version = 2
name = "ducklake"
extension_config = "extension_config_vane.cmake"
build_extensions = ["httpfs", "parquet"]
native_test_selection = "test/sql/vane/native_scan.test"

[vane]
repository = "AstroVela/vane"
revision = "3a85ec3c18ccc0af5d2e0f0183bc851d6443a411"

[vcpkg]
repository = "microsoft/vcpkg"
revision = "84bab45d415d22042bd0b9081aea57f362da3f35"
